version: '3'
services:
  mongodb:
    image: mongo
    restart: always
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
  api:
    image: socialgouv/kaligator-api:latest
    restart: always
    env_file:
      - .env

  extractor:
    image: socialgouv/kaligator-extractor:latest
    env_file:
      - .env
